# Generated by Django 6.0 on 2026-01-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='cakes/')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('bento', 'Bento'), ('vegan', 'Vegan'), ('kids', 'Kids')], max_length=50)),
                ('flavor', models.CharField(max_length=50)),
                ('presentation', models.CharField(max_length=50)),
                ('structure', models.CharField(max_length=50)),
            ],
        ),
    ]
