# Generated by Django 6.0 on 2026-01-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='desserts/')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('pastries', 'Pastries'), ('cookies_biscuits', 'Cookies & Biscuits'), ('brownie', 'Brownie'), ('frozen', 'Frozen'), ('crepes_pancakes', 'Crepes & Pancakes'), ('fruit', 'Fruit'), ('fried', 'Fried'), ('gelatin', 'Gelatin')], max_length=50)),
                ('flavor', models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('fruit', 'Fruit'), ('pistachio', 'Pistachio'), ('strawberry', 'Strawberry'), ('mango', 'Mango')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cake',
            name='presentation',
        ),
    ]
