# Generated by Django 6.0 on 2026-01-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_dessert_remove_cake_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pudding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='puddings/')),
                ('price', models.IntegerField()),
                ('flavor', models.CharField(blank=True, choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('fruit', 'Fruit'), ('pistachio', 'Pistachio'), ('strawberry', 'Strawberry'), ('mango', 'Mango')], max_length=50, null=True)),
                ('style', models.CharField(choices=[('warm', 'Warm'), ('chilled', 'Chilled'), ('vegan', 'Vegan')], default='chilled', max_length=20)),
                ('tag_text', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_color', models.CharField(choices=[('default', 'Default'), ('green', 'Green'), ('vegan', 'Vegan')], default='default', max_length=20)),
            ],
        ),
    ]
