# Generated by Django 6.0 on 2026-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_pudding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_type', models.CharField(choices=[('cake', 'Cake'), ('dessert', 'Dessert'), ('pudding', 'Pudding'), ('sugarfree', 'Sugar Free'), ('gift', 'Gift')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('flavor', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='search/')),
                ('product_id', models.PositiveIntegerField()),
            ],
        ),
    ]
