# Generated by Django 6.0 on 2026-03-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_adminproduct_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productavailability',
            name='product',
        ),
        migrations.RemoveField(
            model_name='area',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='area',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='delivery_person',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productavailability',
            name='pincode',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='AdminProduct',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
        migrations.DeleteModel(
            name='DeliveryAssignment',
        ),
        migrations.DeleteModel(
            name='Pincode',
        ),
        migrations.DeleteModel(
            name='ProductAvailability',
        ),
    ]
