# Generated by Django 6.0 on 2026-01-09 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_type', models.CharField(choices=[('birthday', 'Birthday Cake'), ('wedding', 'Wedding Cake'), ('bento', 'Bento Cake'), ('kids', 'Kids Cake'), ('custom', 'Fully Custom')], max_length=20)),
                ('flavor', models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('redvelvet', 'Red Velvet'), ('butterscotch', 'Butterscotch'), ('fruit', 'Fruit')], max_length=20)),
                ('size', models.CharField(choices=[('0.5kg', '0.5 Kg'), ('1kg', '1 Kg'), ('2kg', '2 Kg'), ('3kg', '3 Kg')], max_length=10)),
                ('message_on_cake', models.CharField(blank=True, max_length=100)),
                ('delivery_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
