# Generated by Django 6.0 on 2026-02-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_size', models.CharField(choices=[('500g', '500g'), ('1kg', '1kg'), ('2kg', '2kg'), ('custom', 'Custom Size')], max_length=20)),
                ('flavor', models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('red_velvet', 'Red Velvet'), ('custom', 'Custom Flavor')], max_length=30)),
                ('cream_type', models.CharField(choices=[('buttercream', 'Buttercream'), ('whipped', 'Whipped Cream'), ('fondant', 'Fondant'), ('custom', 'Custom Cream')], max_length=30)),
                ('custom_size', models.CharField(blank=True, max_length=20, null=True)),
                ('custom_flavor', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_cream', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_photo', models.ImageField(blank=True, null=True, upload_to='cake_photos/')),
                ('message_on_cake', models.CharField(max_length=200)),
                ('delivery_datetime', models.DateTimeField()),
                ('delivery_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomCakeOrder',
        ),
    ]
