# Generated by Django 6.0 on 2026-02-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcake',
            name='ai_preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customcake',
            name='preview_generated',
            field=models.BooleanField(default=False),
        ),
    ]
