# Generated by Django 6.0 on 2026-02-20 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customcake_delete_customcakeorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('flavor', models.CharField(max_length=100)),
                ('cream_type', models.CharField(max_length=100)),
                ('message_on_cake', models.CharField(blank=True, max_length=200)),
                ('reference_photo', models.ImageField(blank=True, null=True, upload_to='cake_photos/')),
                ('delivery_datetime', models.DateTimeField()),
                ('delivery_address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomCake',
        ),
    ]
