# Generated by Django 6.0 on 2026-02-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customcake_ai_preview_customcake_preview_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcake',
            name='delivery_address',
        ),
    ]
