# Generated by Django 6.0 on 2026-02-20 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customcakeorder_delete_customcake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('cake_type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('flavor', models.CharField(max_length=100)),
                ('cream_type', models.CharField(max_length=100)),
                ('message_on_cake', models.CharField(blank=True, max_length=200)),
                ('reference_photo', models.ImageField(blank=True, null=True, upload_to='cake_photos/')),
                ('delivery_datetime', models.DateTimeField()),
                ('delivery_address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_ready_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('baking', 'Baking'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomCakeOrder',
        ),
    ]
