# Generated by Django 6.0 on 2026-02-20 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customcake_delete_customcakeorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customcake',
            old_name='order_id',
            new_name='reference_number',
        ),
        migrations.AddField(
            model_name='customcake',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_cakes', to='orders.order'),
        ),
    ]
