# Generated by Django 6.0 on 2026-02-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_order_id_customcake_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcake',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
