# Generated by Django 6.0 on 2026-01-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='cakes/')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('bento', 'Bento'), ('vegan', 'Vegan'), ('kids', 'Kids')], max_length=50)),
                ('flavor', models.CharField(max_length=50)),
                ('structure', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='desserts/')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('pastries', 'Pastries'), ('cookies_biscuits', 'Cookies & Biscuits'), ('brownie', 'Brownie'), ('frozen', 'Frozen'), ('crepes_pancakes', 'Crepes & Pancakes'), ('fruit', 'Fruit'), ('fried', 'Fried'), ('gelatin', 'Gelatin')], max_length=50)),
                ('flavor', models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('fruit', 'Fruit'), ('pistachio', 'Pistachio'), ('strawberry', 'Strawberry'), ('mango', 'Mango')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_type', models.CharField(choices=[('cake', 'Cake'), ('dessert', 'Dessert'), ('pudding', 'Pudding'), ('sugarfree', 'Sugar Free'), ('gift', 'Gift')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('flavor', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='search/')),
                ('product_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pudding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='puddings/')),
                ('price', models.IntegerField()),
                ('flavor', models.CharField(blank=True, choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('fruit', 'Fruit'), ('pistachio', 'Pistachio'), ('strawberry', 'Strawberry'), ('mango', 'Mango')], max_length=50, null=True)),
                ('style', models.CharField(choices=[('warm', 'Warm'), ('chilled', 'Chilled'), ('vegan', 'Vegan')], default='chilled', max_length=20)),
                ('tag_text', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_color', models.CharField(choices=[('default', 'Default'), ('green', 'Green'), ('vegan', 'Vegan')], default='default', max_length=20)),
            ],
        ),
    ]
