# Generated by Django 6.0 on 2026-02-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='cakes/')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('bento', 'Bento'), ('vegan', 'Vegan'), ('kids', 'Kids')], max_length=50)),
                ('flavor', models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('red-velvet', 'Red Velvet'), ('butterscotch', 'Butterscotch'), ('fruit-cakes', 'Fruit Cakes'), ('cheese_cakes', 'Cheese Cakes')], max_length=50)),
                ('structure', models.CharField(choices=[('single', 'Single Tier'), ('double', 'Double Tier'), ('trible', 'Trible Tier'), ('cupcakes', 'Cup Cakes'), ('sheetcakes', 'Sheet Cakes'), ('spongecakes', 'Sponge Cakes'), ('themecakes', 'Theme Cakes')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='desserts/')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('pastries', 'Pastries'), ('cookies_biscuits', 'Cookies & Biscuits'), ('brownie', 'Brownie'), ('pistachio', 'Pistachio')], max_length=50)),
                ('flavor', models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('fruit', 'Fruit'), ('nutty_caramel', 'Nutty & Caramel')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('product_type', models.CharField(choices=[('cake', 'Cake'), ('dessert', 'Dessert'), ('pudding', 'Pudding')], max_length=20)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('flavor', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, upload_to='search/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pudding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='puddings/')),
                ('price', models.IntegerField()),
                ('flavor', models.CharField(blank=True, choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('fruit', 'Fruit'), ('pistachio', 'Pistachio'), ('strawberry', 'Strawberry'), ('mango', 'Mango'), ('butter', 'Butter')], max_length=50, null=True)),
                ('style', models.CharField(choices=[('warm', 'Warm'), ('chilled', 'Chilled'), ('vegan', 'Vegan')], default='chilled', max_length=20)),
                ('tag_text', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_color', models.CharField(choices=[('default', 'Default'), ('green', 'Green'), ('vegan', 'Vegan')], default='default', max_length=20)),
            ],
        ),
    ]
