# Generated by Django 6.0 on 2026-01-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsearch',
            name='product_type',
            field=models.CharField(choices=[('cake', 'Cake'), ('dessert', 'Dessert'), ('pudding', 'Pudding')], max_length=20),
        ),
    ]
