# Generated by Django 6.0 on 2026-02-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productsearch_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='flavor',
            field=models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('red-velvet', 'Red Velvet'), ('butterscotch', 'Butterscotch'), ('fruit-cakes', 'Fruit Cakes'), ('cheese_cakes', 'Cheese Cakes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cake',
            name='structure',
            field=models.CharField(choices=[('single', 'Single Tier'), ('double', 'Double Tier'), ('cupcakes', 'Cup Cakes'), ('sheetcakes', 'Sheet Cakes'), ('spongecakes', 'Sponge Cakes'), ('themecakes', 'Theme Cakes')], max_length=50),
        ),
    ]
