# Generated by Django 6.0 on 2026-02-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cake_flavor_alter_cake_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pudding',
            name='flavor',
            field=models.CharField(blank=True, choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('fruit', 'Fruit'), ('pistachio', 'Pistachio'), ('strawberry', 'Strawberry'), ('mango', 'Mango'), ('butter', 'Butter')], max_length=50, null=True),
        ),
    ]
