# Generated by Django 6.0 on 2026-02-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_pudding_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='category',
            field=models.CharField(choices=[('pastries', 'Pastries'), ('cookies_biscuits', 'Cookies & Biscuits'), ('brownie', 'Brownie'), ('frozen', 'Frozen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='flavor',
            field=models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('fruit', 'Fruit'), ('nutty_caramel', 'Nutty & Caramel')], max_length=50),
        ),
    ]
