# Generated by Django 6.0 on 2026-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_dessert_category_alter_dessert_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='category',
            field=models.CharField(choices=[('pastries', 'Pastries'), ('cookies_biscuits', 'Cookies & Biscuits'), ('brownie', 'Brownie'), ('pistachio', 'Pistachio')], max_length=50),
        ),
    ]
