# Generated by Django 6.0 on 2026-02-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_dessert_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('wedding', 'Wedding'), ('birthday', 'Birthday'), ('bento', 'Bento'), ('vegan', 'Vegan'), ('kids', 'Kids')], max_length=50),
        ),
    ]
