# Generated by Django 6.0 on 2026-02-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_cake_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='structure',
            field=models.CharField(choices=[('single', 'Single Tier'), ('double', 'Double Tier'), ('trible', 'Trible Tier'), ('cupcakes', 'Cup Cakes'), ('sheetcakes', 'Sheet Cakes'), ('spongecakes', 'Sponge Cakes'), ('themecakes', 'Theme Cakes')], max_length=50),
        ),
    ]
