# Generated by Django 6.0 on 2026-02-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_cake_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('bento', 'Bento'), ('vegan', 'Vegan'), ('kids', 'Kids')], max_length=50),
        ),
    ]
