# Generated by Django 6.0 on 2026-02-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_cake_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsearch',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='tags',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='productsearch',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productsearch',
            name='flavor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productsearch',
            name='image',
            field=models.ImageField(blank=True, upload_to='search/'),
        ),
        migrations.AlterField(
            model_name='productsearch',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productsearch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
